
package interfaz;

import bancoBluePersistencia.daos.clientes.IClientesDAO;
import bancoBluePersistencia.dtos.cliente.ClienteNuevoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class RegistrarseDomicilio extends javax.swing.JFrame {

    ClienteNuevoDTO cliente;
    IClientesDAO clientesDAO;
    /**
     * Creates new form RegistrarseDomicilio
     * @param cliente
     * @param clientesDAO
     */
    public RegistrarseDomicilio(ClienteNuevoDTO cliente, IClientesDAO clientesDAO) {
        this.setUndecorated(true);
        initComponents();
        this.cliente=cliente;
        this.clientesDAO=clientesDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtqCalle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EtqCP = new javax.swing.JLabel();
        EtqColonia = new javax.swing.JLabel();
        EtqMunicipio = new javax.swing.JLabel();
        EtqEstado = new javax.swing.JLabel();
        CmpCalle = new javax.swing.JTextField();
        CmpNumExt = new javax.swing.JTextField();
        CmpCP = new javax.swing.JTextField();
        CmpColonia = new javax.swing.JTextField();
        CmpMunicipio = new javax.swing.JTextField();
        CmpEstado = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EtqCalle.setText("CALLE");

        jLabel2.setText("NÚMERO EXTERIOR");

        EtqCP.setText("C.P.");

        EtqColonia.setText("COLONIA");

        EtqMunicipio.setText("MUNICIPIO");

        EtqEstado.setText("ESTADO");

        CmpCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmpCalleActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.setMaximumSize(new java.awt.Dimension(193, 63));
        btnSiguiente.setMinimumSize(new java.awt.Dimension(193, 63));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EtqCalle)
                                .addGap(137, 137, 137))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EtqColonia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CmpCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CmpColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EtqMunicipio)
                    .addComponent(jLabel2)
                    .addComponent(CmpNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmpMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmpEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmpCP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtqCP)
                    .addComponent(EtqEstado))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtqCalle)
                    .addComponent(jLabel2)
                    .addComponent(EtqCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmpCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmpNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmpCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtqColonia)
                    .addComponent(EtqMunicipio)
                    .addComponent(EtqEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmpColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmpMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmpEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CmpCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmpCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmpCalleActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // Obtener valores de los campos
        String codigoPostalStr = this.CmpCP.getText();
        String calle = this.CmpCalle.getText();
        String colonia = this.CmpColonia.getText();
        String estado = this.CmpEstado.getText();
        String municipio = this.CmpMunicipio.getText();
        String numExtStr = this.CmpNumExt.getText();

        // Comprobar que ningún campo sea null o esté vacío
        if (codigoPostalStr != null && calle != null && colonia != null
                && estado != null && municipio != null && numExtStr != null
                && !codigoPostalStr.isEmpty() && !calle.isEmpty() && !colonia.isEmpty()
                && !estado.isEmpty() && !municipio.isEmpty() && !numExtStr.isEmpty()) {

            int codigoPostal=0;
            int numExt=0;
            try {
                codigoPostal = Integer.parseInt(this.CmpCP.getText());
                numExt = Integer.parseInt(this.CmpNumExt.getText());

                // Verificar que ambos valores son números válidos antes de continuar
                if (codigoPostal < 0 || numExt < 0) {
                    JOptionPane.showMessageDialog(this, "El código postal y el número exterior deben ser números positivos.", "Error", JOptionPane.ERROR_MESSAGE);
                    return; // Sale del método si hay un error
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, ingresa números válidos para el código postal y el número exterior.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Configurar los valores en el objeto cliente
            cliente.setCalle(calle);
            cliente.setColonia(colonia);
            cliente.setCodigoPostal(codigoPostal);
            cliente.setEstado(estado);
            cliente.setCiudad(municipio);
            cliente.setNumExterior(numExt);

            // Realizar la acción si todos los campos son válidos
            if (true) {
                RegistrarseUsuario registrar = new RegistrarseUsuario(cliente, clientesDAO);
                registrar.setVisible(true);
            }
        } else {
            // Mostrar un mensaje de error o realizar alguna otra acción
            // porque algunos campos son null o están vacíos
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        }

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CmpCP;
    private javax.swing.JTextField CmpCalle;
    private javax.swing.JTextField CmpColonia;
    private javax.swing.JTextField CmpEstado;
    private javax.swing.JTextField CmpMunicipio;
    private javax.swing.JTextField CmpNumExt;
    private javax.swing.JLabel EtqCP;
    private javax.swing.JLabel EtqCalle;
    private javax.swing.JLabel EtqColonia;
    private javax.swing.JLabel EtqEstado;
    private javax.swing.JLabel EtqMunicipio;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
