
package interfaz;

import bancoBluePersistencia.daos.clientes.IClientesDAO;
import bancoBluePersistencia.dtos.cliente.ClienteNuevoDTO;
import bancoBluePersistencia.excepciones.PersistenciaException;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class RegistrarseUsuario extends javax.swing.JFrame {

    ClienteNuevoDTO cliente;
    IClientesDAO clientesDAO;
    /**
     * Creates new form RegistrarseUsuario
     * @param cliente
     * @param clientesDAO
     */
    public RegistrarseUsuario(ClienteNuevoDTO cliente, IClientesDAO clientesDAO) {
        this.setUndecorated(true);
        initComponents();
        this.cliente=cliente;
        this.clientesDAO=clientesDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        EtqNombreUsuario = new javax.swing.JLabel();
        CmpNombreUsuario = new javax.swing.JTextField();
        EtqContrasenia = new javax.swing.JLabel();
        CmpContrasenia = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnGuardar.setBackground(new java.awt.Color(238, 107, 107));
        btnGuardar.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(193, 63));
        btnGuardar.setMinimumSize(new java.awt.Dimension(193, 63));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(450, 330, 193, 63);

        EtqNombreUsuario.setText("NOMBRE DE USUARIO");
        getContentPane().add(EtqNombreUsuario);
        EtqNombreUsuario.setBounds(53, 134, 118, 16);
        getContentPane().add(CmpNombreUsuario);
        CmpNombreUsuario.setBounds(53, 156, 184, 22);

        EtqContrasenia.setText("CONTRASEÑA");
        getContentPane().add(EtqContrasenia);
        EtqContrasenia.setBounds(53, 249, 76, 16);
        getContentPane().add(CmpContrasenia);
        CmpContrasenia.setBounds(53, 271, 184, 22);

        btnVolver.setBackground(new java.awt.Color(238, 107, 107));
        btnVolver.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(10, 10, 191, 63);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String contrasenia = this.CmpContrasenia.getText();
        String nombreUsuario = this.CmpNombreUsuario.getText();

        if (contrasenia != null && !contrasenia.isEmpty() && nombreUsuario != null && !nombreUsuario.isEmpty()) {
            cliente.setNombreUsuario(nombreUsuario);
            cliente.setContrasenia(contrasenia);
            try {
                if (clientesDAO.validarNombreUsuarios(nombreUsuario)) {

                } else {
                    JOptionPane.showMessageDialog(this, "Nombre de usuario en uso");
                    return;
                }

            } catch (PersistenciaException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo agregar el socio debido a un error en la base de datos");
            }
            try {
                clientesDAO.agregar(cliente);
                JOptionPane.showMessageDialog(this, "Se agrego el socio");
                this.dispose();
            } catch (PersistenciaException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo agregar el socio debido a un error en la base de datos");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CmpContrasenia;
    private javax.swing.JTextField CmpNombreUsuario;
    private javax.swing.JLabel EtqContrasenia;
    private javax.swing.JLabel EtqNombreUsuario;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    // End of variables declaration//GEN-END:variables
}
